### ISSUE TITLE
Erros encountered at yarn build step when trying to run in Dockerfile 

### ISSUE THREAD

**Issue by quaxquax** [jtpio/jupyterlite#105]
## Description
After successfully completing the `RUN yarn` step `RUN yarn build` results in the following error:

```
@jupyterlite/app-lab: [webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve '../py/pyolite/dist/pyolite-0.1.0-py3-none-any.whl' in '/jupyterlite/packages/pyolite-kernel/lib'
@jupyterlite/app-lab:     at /jupyterlite/node_modules/webpack/lib/Compilation.js:1672:28
@jupyterlite/app-lab:     at /jupyterlite/node_modules/webpack/lib/NormalModuleFactory.js:712:13
@jupyterlite/app-lab:     at eval (eval at create (/jupyterlite/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
@jupyterlite/app-lab:     at /jupyterlite/node_modules/webpack/lib/NormalModuleFactory.js:273:22
@jupyterlite/app-lab:     at eval (eval at create (/jupyterlite/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
@jupyterlite/app-lab:     at /jupyterlite/node_modules/webpack/lib/NormalModuleFactory.js:402:22
@jupyterlite/app-lab:     at /jupyterlite/node_modules/webpack/lib/NormalModuleFactory.js:117:11
@jupyterlite/app-lab:     at /jupyterlite/node_modules/webpack/lib/NormalModuleFactory.js:628:24
@jupyterlite/app-lab:     at /jupyterlite/node_modules/webpack/lib/NormalModuleFactory.js:782:8
@jupyterlite/app-lab:     at /jupyterlite/node_modules/webpack/lib/NormalModuleFactory.js:902:5
@jupyterlite/app-lab: resolve '../py/pyolite/dist/pyolite-0.1.0-py3-none-any.whl' in '/jupyterlite/packages/pyolite-kernel/lib'
@jupyterlite/app-lab:   using description file: /jupyterlite/packages/pyolite-kernel/package.json (relative path: ./lib)
@jupyterlite/app-lab:     Field 'browser' doesn't contain a valid alias configuration
@jupyterlite/app-lab:     using description file: /jupyterlite/packages/pyolite-kernel/package.json (relative path: ./py/pyolite/dist/pyolite-0.1.0-py3-none-any.whl)
@jupyterlite/app-lab:       no extension
@jupyterlite/app-lab:         Field 'browser' doesn't contain a valid alias configuration
@jupyterlite/app-lab:         /jupyterlite/packages/pyolite-kernel/py/pyolite/dist/pyolite-0.1.0-py3-none-any.whl doesn't exist
```
I noticed that the file reported missing i.e. `./py/pyolite/dist/pyolite-0.1.0-py3-none-any.whl` is indeed missing in the repo. Not sure if this python wheel is supposed to be created in an earlier step that I am missing?

## Reproduce

If you perform a `docker built .` with the following Dockerfile you should get the error above:

```
FROM condaforge/mambaforge:latest

RUN git clone https://github.com/jtpio/jupyterlite
WORKDIR jupyterlite

#Installing required tools
RUN mamba env update --file .binder/environment.yml

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "jupyterlite-dev", "/bin/bash", "-c"]

RUN yarn
RUN yarn build
```

I confirmed that the installed yarn is a 1.x version, also ran the image interactively to see if would get a different behavior runnng the command from the terminal and ensuring that the correct python environment was active. Gave same result.

## Expected behavior

My expectation was to complete the `yarn built` steps without errors.

## Context

- Operating System and version: Ubuntu 20.04.
- Browser and version:
- JupyterLite version: Current git snapshot

**Comment by jtpio** [comment]
Thanks @quaxquax for the report.

It looks like it's related to the pyolite wheel not being built.

Maybe you could try using the `doit` commands to set up the environment from source, which should also build the wheel: https://jupyterlite.readthedocs.io/en/latest/contributing.html#task-and-action-defaults

Or run the task explicitly with `doit build:py:pyolite`.

**Comment by bollwyvl** [comment]
Right.

Much like make, doit and docker work pretty well together... depending on
your goal (final image size vs good caching for development vs simplicity,
pick one, maybe), you can either

RUN doit

Or, after seeing the order of the tasks:

RUN doit thing:one
RUN doit thing:two

Or use a multi-stage image and copy the final assets out into something
like the official nginx image.

Note that a "stock" build has no lab extensions not developed in this repo,
and no starting content.

While this is the focus of #41, is possible today. To add more, as we do on
the docs site, the simplest approach might be to

RUN conda install some-extension
RUN doit
COPY ["some.ipynb", "other.py", "examples"]
RUN doit docs

And the full application (plus your stuff) will be in docs/_build/_static

**Comment by quaxquax** [comment]
Thanks for the very helpful replies! Running `doit` got me unstuck.

**Comment by lorenzo-leuck** [comment]
> Thanks for the very helpful replies! Running `doit` got me unstuck.

Can you share the commands you used in dockerfile?

**Comment by jtpio** [comment]
@lorenzo-leuck `jupyterlite` is now published on PyPI: https://pypi.org/project/jupyterlite/

We recommend using the `jupyterlite` CLI instead of cloning the repo and building from source.

More info in the docs: https://jupyterlite.readthedocs.io/en/latest/cli.html#installation

**Comment by lorenzo-leuck** [comment]
Thanks @jtpio ! Unfortunately the PyPI approach doesnt work in windows. From what I searched here in this repository, it's because of some directory error regarding "//"
