### ISSUE TITLE
Pyolite crashes randomly

### ISSUE THREAD

**Issue by martinRenou** [jtpio/jupyterlite#158]
## Description

When using the Pyolite kernel and executing code, it happens randomly that the page crashes with this error message:

![crash](https://user-images.githubusercontent.com/21197331/122535660-0f5bb300-d024-11eb-9a90-659be0893e7c.png)

**Comment by jtpio** [comment]
Thanks Martin.

I remember seeing those a while ago before this issue was fixed: https://github.com/pyodide/pyodide/issues/1384

But not anymore after updating Pyodide to the final `0.17.0` release.

**Comment by martinRenou** [comment]
I guess my laptop does not have enough memory. It seems to happen especially when loading data.

**Comment by jtpio** [comment]
Do you have a code snippet that we could post here for reference? (if that's reproducible)

**Comment by martinRenou** [comment]
```python
import pandas as pd

from js import fetch

URL = "https://raw.githubusercontent.com/jupyter-widgets/ipyleaflet/master/examples/nations.json"

res = await fetch(URL)
text = await res.text()

data = pd.read_json(text)
```

seems to be a good reproducer for me locally

**Comment by jtpio** [comment]
OK thanks for sharing :+1: 

This seems to be fine on my machine with the demo website:

![image](https://user-images.githubusercontent.com/591645/122538496-e7ba1a00-d026-11eb-80af-bf9870552ad4.png)

**Comment by martinRenou** [comment]
I am using Brave with Chromium: 90.0.4430.212. I will see if upgrading my browser can fix it.

**Comment by martinRenou** [comment]
It seems to work perfectly on Firefox on my side though!

**Comment by jtpio** [comment]
Which version for Firefox?

**Comment by martinRenou** [comment]
88.0.1

**Comment by martinRenou** [comment]
I don't seem to be able to replicate the issue after upgrading to Brave 1.25.73 Chromium: 91.0.4472.106. Let's close this.

**Comment by qqdaiyu55** [comment]
Jupytelite Version: 0.1.0-alpha.6
The page could randomly brreak down. Before that, I could see below error
```
pyodide.asm.js:9 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 419, in eval_code_async
    return await CodeRunner(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 272, in run_async
    await coro
  File "<exec>", line 2, in <module>
  File "/lib/python3.8/site-packages/micropip.py", line 10, in <module>
    from packaging.requirements import Requirement
  File "/lib/python3.8/site-packages/packaging/requirements.py", line 10, in <module>
    from pyparsing import (  # noqa: N817
MemoryError

    at new_error (pyodide.asm.js:9)
    at pyodide.asm.wasm:0x1a6c94
    at pyodide.asm.wasm:0x1aaab3
    at pyodide.asm.wasm:0x7a257c
    at pyodide.asm.wasm:0x1cabed
    at pyodide.asm.wasm:0x2c54f1
    at pyodide.asm.wasm:0x7bf866
    at pyodide.asm.wasm:0x21220e
    at pyodide.asm.wasm:0x7bdce6
    at pyodide.asm.wasm:0x1cb006
```
