### ISSUE TITLE
Publish release assets via GitHub releases

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlite#16]
During the release process, the static assets can be published as release assets so it's easy for anyone to download them and serve the content of the tarball right away with a simple web server.

**Comment by bollwyvl** [comment]
Hm, erring on the side of "don't reinvent things," how do we feel about adding a `package.json` to `app/`, calling _that_ `@jupyterlite/app` (renaming `lab` to `app-lab`) and then using `npm pack`? it wouldn't be a real package, per se, but would handle a lot of stuff (e.g. naming it well).

**Comment by bollwyvl** [comment]
One quirk is that the tarball has a `package/` folder... but at least it's _always_ called that.

**Comment by jtpio** [comment]
> renaming `lab` to `app-lab`

Done in https://github.com/jtpio/jupyterlite/pull/54

**Comment by jtpio** [comment]
> it wouldn't be a real package, per se, but would handle a lot of stuff (e.g. naming it well).

I was thinking of a plain `zip` or `tarball` command, but if we can get naming and metadata then sure.

**Comment by bollwyvl** [comment]
Further while talking about release assets... Right now, the release is
about 14mb, 64 uncompressed. A huge proportion of that is the duplication
of large assets in lab/build and classic/build. It's probably worth
exploring how to get as much as possible to end up in ../static, relative
to each of them.

**Comment by jtpio** [comment]
> A huge proportion of that is the duplication of large assets in lab/build and classic/build

The idea was to keep both lab and classic in the same repo for now (so it's easier to iterate on), and then move classic to another repo (for example called `jupyterlite-classic`) to demonstrate how to build a custom JupyterLite distribution using the published `@jupyterlite` packages.

But maybe we should actually just ship lab and classic together always? Similar to core lab currently bringing `nbclassic`. Folks can then chose the interface they want. In that case we could indeed try to merge the two build folders into one, which hopefully will help reduce the final size.

**Comment by bollwyvl** [comment]
Maybe they can both be shipped, but then (either) be easily disabled by a `.jupyterlite#/apps` setting? 

Down the road, I see something like an `app-book` that quacks more like a traditional docs site, or `app-slides` that presents things like presentations, and could see wanting expose exactly one, or many different views, with the ability to switch between them.

**Comment by bollwyvl** [comment]
We now at least have the app tarball on actions:
https://github.com/jtpio/jupyterlite/actions/runs/785753201


We could add a gated job at the end of it that only runs on tags which can make a release... and maybe unpack the intermediate `package` folder.
