### ISSUE TITLE
Failing windows check on CI

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlite#174]
Looks like the windows build job is now failing on CI during the `pip install -U pip setuptools wheel` step: https://github.com/jtpio/jupyterlite/runs/2931131528

![image](https://user-images.githubusercontent.com/591645/123628404-57908780-d813-11eb-907c-b62349895650.png)

Maybe one of the suspects could be the new version of pip (`21.1.3`) released 2 days ago: https://pypi.org/project/pip/21.1.3/

**Comment by bollwyvl** [comment]
WINDOWS!
