### ISSUE TITLE
Missing README on the PyPI page

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlite#183]
`jupyterlite` is now available on PyPI: https://pypi.org/project/jupyterlite/

However the page would look nice with the readme.

![image](https://user-images.githubusercontent.com/591645/123693773-c5ab6d80-d858-11eb-8e50-7c3786f2a519.png)

We could for example use the top-level readme file.

**Comment by bollwyvl** [comment]
yeah, that's on me. rookie mistake. we can add `check-manifest` and `twine check`, etc. will do this evening if nobody beats me to it...
