### ISSUE TITLE
broken doit?

### ISSUE THREAD

**Issue by madhur-tandon** [jtpio/jupyterlite#185]
## Description

Running `doit` used to build the setup locally. However, with the latest `main` branch, it gives
```
ERROR: Invalid parameter: "schema". Must be a command, task, or a target.
Type "doit help" to see available commands.
Type "doit list" to see available tasks.
```

Running `doit build` does the job though.

**Comment by bollwyvl** [comment]
Moved schema to lint... You can see all the stuff it will do with:

doit list --all --status

**Comment by jtpio** [comment]
Probably the default `doit` tasks can run the tasks like before, so it's consistent with the docs: https://jupyterlite.readthedocs.io/en/latest/contributing.html#task-and-action-defaults

(or we update the docs)

**Comment by bollwyvl** [comment]
oh, snap, yeah, that's my bad on not updating the `default_tasks`. We should add the `docs:app:build` to it as well. PR incoming...
