### ISSUE TITLE
Refactor kernel's executeResult and executeError handling

### ISSUE THREAD

**Issue by martinRenou** [jtpio/jupyterlite#211]
### Problem

As discovered in @madhur-tandon 's IPython PR (https://github.com/jtpio/jupyterlite/pull/171), the `executeResult` is handled in the base kernel [here](https://github.com/jtpio/jupyterlite/blob/ad01d63864a46a9166632cdf73e676490d5e0c50/packages/kernel/src/kernel.ts#L345), but handling `executeResult` and `executeError` should be kernel specific. For example, when using IPython in pyolite, we'll let IPython's display hook trigger the `executeResult`.

We need to refactor this a bit.

You can assign this task to me if you want.

**Comment by martinRenou** [comment]
The implementation of the execute-request in the base kernel should not try to handle other kinds of messages, it should just answer with the execute-reply

**Comment by jtpio** [comment]
Sounds good. I think this TODO item is also related:

https://github.com/jtpio/jupyterlite/blob/74406c8698ace3fc0c5a3b7cecfbd080039e5cba/packages/pyolite-kernel/src/kernel.ts#L197

**Comment by jtpio** [comment]
> You can assign this task to me if you want.

Thanks Martin! Just assigned it to you but feel free to comment here if you would like to let it go, no problem.

**Comment by martinRenou** [comment]
Working on it right now
