### ISSUE TITLE
macos CI failing

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlite#215]
## Description

Looks like CI is now failing on macos: https://github.com/jtpio/jupyterlite/runs/2998239544

Started on this commit: https://github.com/jtpio/jupyterlite/commit/99dcbe7e445901bd09b34b7f0a19ca13af37312a

This is also happening on new PRs; https://github.com/jtpio/jupyterlite/pull/214/checks?check_run_id=2998598392

**Comment by jtpio** [comment]
Yes this one looks very random, since all the previous commits have been fine so far.

> Should we just skip the `serve` tests on OSX?

Sounds good :+1:

**Comment by jtpio** [comment]
Just restarted the checks on `main` and they are now passing :man_shrugging: 

![image](https://user-images.githubusercontent.com/591645/124610223-9ad0a300-de70-11eb-8c26-8376ee6cf0f4.png)

**Comment by bollwyvl** [comment]
Right, that is the mystery of :snowflake:. But as we:

- can't restart _just_ osx
- can't reproduce locally (lacking hardware)
- are using CI to actually ship software

I don't see a quick win that keeps the machine running other than skipping, in this case, much as it pains me.
