### ISSUE TITLE
Create a set of example notebooks

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlite#30]
These example notebooks could be added to the local storage by default (so available in the file browser on the first startup), and be used to quickly showcase a specific feature of a kernel or the language.

**Comment by jtpio** [comment]
For now maybe the simplest would be to have:

- a new `examples-extension` package, with a plugin that depends on the [IContents](https://github.com/jtpio/jupyterlite/blob/1b402f869ac6d72507b12c0fa05075f72f4fd7b6/packages/contents/src/tokens.ts#L15) service
- a set of notebooks in `packages/examples-extension/notebooks`, as normal `.ipynb` files with the correct metadata already populated (so it starts the right kernel)
- on build, notebooks are placed under `app/examples/notebooks` as-is
- on plugin activation, `@jupyterlite/examples` fetch the examples and adds them to the local storage with [contents.save()](https://github.com/jtpio/jupyterlite/blob/1b402f869ac6d72507b12c0fa05075f72f4fd7b6/packages/contents/src/contents.ts#L290)
- to be less disruptive, they could even be placed under an `examples/`directory:

![image](https://user-images.githubusercontent.com/591645/115048431-d98e3700-9ed9-11eb-9ab1-2b3d67c593d5.png)

**Comment by bollwyvl** [comment]
This is the part where folk will want to be able to put their stuff in and
all but _instantly_ get a working site, with notebooks, file assets, data
sets, that work with markdown, image viewers, etc. I see this as realizing
the /api/contents route, even if the _actual_ contents stay in their native
format.

As hinted at on #41, I think the part where one adds contents should
definitely not require webpack, nor should examples be shipped as part of
the distributed base assets. Really just should need to build up the JSON
tree, which should be doable in node or python (or whatever).
