### ISSUE TITLE
Serve wasm file with the `application/wasm` mime type

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlite#59]
This doesn't seem to be the case at the moment when serving Pyodide from a local server started with `yarn serve` (which uses [`http-server`](https://www.npmjs.com/package/http-server)):

![image](https://user-images.githubusercontent.com/591645/115741745-4e58e980-a390-11eb-816d-034862befb7c.png)

**Comment by bollwyvl** [comment]
Lame, there's been a PR open for two years to fix this. #62 is a stopgap solution: seems like a junk dev server is preferable to another couple hundred packages.

**Comment by jtpio** [comment]
Fixed by https://github.com/jtpio/jupyterlite/pull/62
