### ISSUE TITLE
Improve previews and auto-deploys on Vercel with more control on the build step

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlite#63]
### Problem

At the moment it's really convenient to be able to open a PR and have the bot post a link to the preview. As well as having JupyterLite automatically be published to https://jupyterlite.vercel.app when the PR is merge into the `main` branch.

With https://github.com/jtpio/jupyterlite/pull/57 we however start having a more complex build system that also involves Python dependency management. And adding Python makes the Vercel configuration more complicated (also difficult to get it to work).

### Proposed Solution

It would be interesting to start using this action: https://github.com/amondnet/vercel-action.

Looks like we would get everything needed:

- comment on new PRs with a link to the preview
- full control on the build and its dependencies via GitHub Actions workflows
- the app is still pushed to Vercel just like it is no

The other option mentioned in #57 was to deploy to GitHub Pages instead, using something like https://github.com/marketplace/actions/deploy-to-github-pages (not sure it would be easy to have a preview with this approach)

### Additional context

Questions mostly coming from the iterations in https://github.com/jtpio/jupyterlite/pull/57.

**Comment by bollwyvl** [comment]
How about readthedocs? It's per-pr thing works great, works with conda so
we can have our js and py (and maybe other languages in the future)... And
we'd get docs! It can also be configured for multiple versions and
languages, vs having to home roll something.

Further, rtd is used by many languages and packages already, helping with
#41... and if you're deploying a sandbox, it would look sharp for it to be
attached to your docs, and get the same features.

**Comment by jtpio** [comment]
Ah good point!

And they have a nice GitHub integration with previews too. For example:

![image](https://user-images.githubusercontent.com/591645/115927802-4cbd1d80-a485-11eb-931f-704eaa9770d8.png)

So yeah this might be the simplest actually.

**Comment by bollwyvl** [comment]
Cool, sounds good.

If you set up the account, it's probably worth asking for the mamba feature
flag immediately:

https://docs.readthedocs.io/en/stable/guides/feature-flags.html

In the "deploying jupyterlite" section of the (eventual) actual docs, it is
probably worth still mentioning vercel...

**Comment by jtpio** [comment]
> If you set up the account, it's probably worth asking for the mamba feature flag immediately:

If I read this correctly, this must be requested by email?

> A separate request can be made by contacting us via email to enable or disable one or more of these featured flags for a particular project.

**Comment by jtpio** [comment]
Just set up: https://jupyterlite.readthedocs.io/en/latest/

**Comment by bollwyvl** [comment]
Yeah it's an email. Weird.

**Comment by bollwyvl** [comment]
Anyhow: if you had some notes on the federated junk, I'm more than happy to
start digging into docs/pipes/builds, since I wasn't making a lot of
headway.

Funny story: I demoed running robot framework inside polite today... Pretty
insane.

**Comment by jtpio** [comment]
Got the confirmation the mamba flag has been enabled.

**Comment by bollwyvl** [comment]
Looks like the remaining things here:
- change references to previous vercel links to https://jupyterlite.readthedocs.io
  - README.md
  - Github project URL
  - set `homepage`, etc in various metadata spots

**Comment by jtpio** [comment]
>  set homepage, etc in various metadata spots

Do you think `homepage` should point to RTD? Or to the URL of the repo (like it seems to be for now)?

**Comment by bollwyvl** [comment]
One pro: if we get it hoisted to another, non-personal repo (even after release), at least the home URL would stay the same. It's less weird if the dev url changes, probably, because developers.

**Comment by jtpio** [comment]
> One pro: if we get it hoisted to another, non-personal repo

Yes we should move it somewhere else at some point. Probably something for another issue though. I created the [jupyterlite](github.com/jupyterlite) org on GitHub a while ago just in case. This could be a good place to have other `lite` stuff there too like other kernels, demo repos and more.

**Comment by bollwyvl** [comment]
I dig. No hurry. Good job on the demo.

I'm going to take a break and ship some other stuff. I feel like to be in a shippable state (whatever that means at this point) here, we need...

- a unified, deduplicated build of lab and classic to get the tarball size down
  - or two tarballs, with a check to disable the potentially confusing cross-app links
- `/lab/extensions`
- `/files` and derived `/api/contents`
- maybe the schema (documented)

...with at least a manual, documented way, not involving webpack, of getting stuff into a gh-pages/rtd-deployable state, given the janky CI artifact. then we can really start digging into stuff!

**Comment by bollwyvl** [comment]
I think with the secrets situation here, vercel deploys will make sense for certain kinds of projects, but we'd want to point out some of the shortcomings w/r/t python upstreams. I'll hoist the deduplication to a new issue.

**Comment by jtpio** [comment]
Maybe we can actually remove the Vercel deploy workflow from this repo.

The RTD setup has been working well so far, so we could just document the Vercel case in the docs.
