### ISSUE TITLE
URL issues with JupyterLab Classic

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlite#73]
## Description

Opening a new issue to track this comment: https://github.com/jtpio/jupyterlite/pull/64#issuecomment-826630567

The `/tree` redirect doesn't seem to work on Binder or when serving locally with `yarn serve`:

![image](https://user-images.githubusercontent.com/591645/116053452-fe716f80-a67a-11eb-8f9a-3ab96b76b1ac.png)

There also seems to be a redirect / base url issue on RTD:

https://user-images.githubusercontent.com/591645/116255320-6b1b6580-a772-11eb-915e-775adb6c8f21.mp4

Although direct access to https://jupyterlite.readthedocs.io/en/latest/_static/classic/index.html is fine.

## Reproduce

https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html

**Comment by bollwyvl** [comment]
gah, right... on it right now, and will do the "pretty" links for docs

**Comment by bollwyvl** [comment]
the python http.server still can't handle an unslashed tree URL. really, if
we could get upstream to redirect to `{baseUrl}tree/` this would be DONE
done.
