### ISSUE TITLE
Allow overriding plugin settings 

### ISSUE THREAD

**Issue by bollwyvl** [jtpio/jupyterlite#81]
### Problem

When deploying a JupyterLite, some default settings might not be right for the use case of a particular deployment. It should be easy to finely-tune default settings, down the tool level (e.g. use one theme in `/lab`, and another in `/classic/notebooks` and _another_ in `/classic/editor`).

### Proposed Solution

Building on #58, add a new section to `jupyter-lite.json` that has the same structure as `overrides.json` (no JSON5, thanks!). So to disable the modal command palette:

```json
{
  "jupyter-lite-schema-version": 0,
  "jupyter-config-data": {},
  "settings-overrides": {
    "@jupyterlab/apputils-extension:palette": {"modal": false}
  }
}
```

Alternately, these could right into `jupyter-config-data`, but it wouldn't be "canonical"...

### Additional context

Wherever it lands, the Schema `definition` would be something like:

```json
"settings-overrides": {
  "description": "plugin-keyed settings that replace the defaults. See https://jupyterlab.readthedocs.io/en/stable/user/directories.html#overrides-json",
  "type": "object",
  "patternProperties": {
    "that-enormous-regex:.*": {
      "type": "object"
    }
  }
}
```

In `settings.ts`, these would be read either by `PageConfig` (simple) or we have equivalent `jupyter-lite.json` reading equipment on the "app" side (more flexible).

**Comment by jtpio** [comment]
> add a new section to `jupyter-lite.json` that has the same structure as `overrides.json` (no JSON5, thanks!).

Sounds good :+1: If we can keep most of the configuration system similar to what JupyterLab already does, it should hopefully help keep things simple (and help documenting this).

**Comment by bollwyvl** [comment]
Another approach might be to know about `overrides.json` in each folder, merging them upwards... it's more http requests that could 404, though...

**Comment by bollwyvl** [comment]
Starting this now, going to keep in in `jupyter-lite.json` for the time being.
