### ISSUE TITLE
Render Matplotlib Figure Example

### ISSUE THREAD

**Issue by owenlamont** [jtpio/jupyterlite#85]
### Problem

I couldn’t figure out how to render a matplotlib figure in a notebook and don’t know if this is supported yet.

### Proposed Solution

If figure rendering is supported can an example be shown in these documentation - if unsupported can this also be noted in the documentation.

**Comment by jtpio** [comment]
Thanks @owenlamont for the interest!

There will soon be example notebooks available on the [demo website](https://jupyterlite.rtfd.io/en/latest/try/lab) (#30).

In the meantime there is this gist with some info: https://gist.github.com/jtpio/3ba7feacc67431488e33a148429f96f1

You can download the notebook and then upload it via the JupyterLab interface if you would like to try it out:

![image](https://user-images.githubusercontent.com/591645/117410271-7d379980-af12-11eb-8661-c719336dc33f.png)


For now `matplotlib` in JupyterLite is pretty basic but should at least work with simple plots as static pngs. The Pyolite kernel currently runs in a web worker so interactivity is not supported yet. A sample code snippet would like this:

```python
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10, 1000)
plt.plot(x, np.sin(x));

plt.show()
```

There is ongoing work to make this better:

- add support for ipywidgets for JupyterLite: #18 
- canvas based renderer for matplotlib in Pyodide: https://github.com/pyodide/pyodide/pull/1579

**Comment by owenlamont** [comment]
Cheers! Thanks for the examples. 

I got a little caught out expecting the current Jupyter lab behavior of auto rendering Matplotlib figures - I tried the old Matplotlib inline magic then realised magics don't seem to be parsed.

I was trying the Pandas DataFrame plot method and was wondering why I couldn't see anything.

**Comment by jtpio** [comment]
The default Python kernel is indeed pretty minimal at the moment. So quite a few common things are still missing.

Ideally, it will be possible to reuse some of the features from existing kernels and `IPython`.

**Comment by bollwyvl** [comment]
@owenlamont as of earlier today the `examples/` folder on the docs site (give it a good hard refresh!) should now show a minimal example of using matplotlib in pyolite. magics will come soon enough!

**Comment by owenlamont** [comment]
Fantastic, thank you very much.

**Comment by bollwyvl** [comment]
Going to close this, please reopen if you have any other concerns!
